#!/bin/python3

import random

print('''
Generatore di Password
By Beard Developer
==================
''')

chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!@£$%^&*().,?0123456789'

number = input('Numero di password?')
number = int(number)

length = input('Lunghezza password?')
length = int(length)

print('Queste sono le tue password:')

for pwd in range(number):
  password = ''
  for c in range(length):
    password += random.choice(chars)
  print(password)
